/** @file cmdline.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.22.6
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt by Lorenzo Bettini */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE "trivial_renderer"
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define CMDLINE_PARSER_PACKAGE_NAME "trivial_renderer"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION "0.1"
#endif

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  char * input_arg;	/**< @brief Archivo a leer.  */
  char * input_orig;	/**< @brief Archivo a leer original value given at command line.  */
  const char *input_help; /**< @brief Archivo a leer help description.  */
  char * output_arg;	/**< @brief Archivo de salida.  */
  char * output_orig;	/**< @brief Archivo de salida original value given at command line.  */
  const char *output_help; /**< @brief Archivo de salida help description.  */
  char * resolution_arg;	/**< @brief Resolución de la imagen en la forma <x,y>.  */
  char * resolution_orig;	/**< @brief Resolución de la imagen en la forma <x,y> original value given at command line.  */
  const char *resolution_help; /**< @brief Resolución de la imagen en la forma <x,y> help description.  */
  const char *raster_wireframe_help; /**< @brief Raster wireframe a hacer help description.  */
  char * viewport_arg;	/**< @brief Rectángulo que acota al modelo 3D en la imagen(Esta opción desactiva scale y translate).  */
  char * viewport_orig;	/**< @brief Rectángulo que acota al modelo 3D en la imagen(Esta opción desactiva scale y translate) original value given at command line.  */
  const char *viewport_help; /**< @brief Rectángulo que acota al modelo 3D en la imagen(Esta opción desactiva scale y translate) help description.  */
  char * rotate_arg;	/**< @brief Rotación con respecto al eje x,y,z en grados.  */
  char * rotate_orig;	/**< @brief Rotación con respecto al eje x,y,z en grados original value given at command line.  */
  const char *rotate_help; /**< @brief Rotación con respecto al eje x,y,z en grados help description.  */
  char * scale_arg;	/**< @brief Escalar la figura en x,y,z.  */
  char * scale_orig;	/**< @brief Escalar la figura en x,y,z original value given at command line.  */
  const char *scale_help; /**< @brief Escalar la figura en x,y,z help description.  */
  char * translate_arg;	/**< @brief Trasladar a un punto (x,y,z).  */
  char * translate_orig;	/**< @brief Trasladar a un punto (x,y,z) original value given at command line.  */
  const char *translate_help; /**< @brief Trasladar a un punto (x,y,z) help description.  */
  char * rotate_x_arg;	/**< @brief Rotación con respecto al eje x en grados.  */
  char * rotate_x_orig;	/**< @brief Rotación con respecto al eje x en grados original value given at command line.  */
  const char *rotate_x_help; /**< @brief Rotación con respecto al eje x en grados help description.  */
  char * rotate_y_arg;	/**< @brief Rotación con respecto al eje y en grados.  */
  char * rotate_y_orig;	/**< @brief Rotación con respecto al eje y en grados original value given at command line.  */
  const char *rotate_y_help; /**< @brief Rotación con respecto al eje y en grados help description.  */
  char * rotate_z_arg;	/**< @brief Rotación con respecto al eje z en grados.  */
  char * rotate_z_orig;	/**< @brief Rotación con respecto al eje z en grados original value given at command line.  */
  const char *rotate_z_help; /**< @brief Rotación con respecto al eje z en grados help description.  */
  char * scale_x_arg;	/**< @brief Escalar la figura en x.  */
  char * scale_x_orig;	/**< @brief Escalar la figura en x original value given at command line.  */
  const char *scale_x_help; /**< @brief Escalar la figura en x help description.  */
  char * scale_y_arg;	/**< @brief Escalar la figura en y.  */
  char * scale_y_orig;	/**< @brief Escalar la figura en y original value given at command line.  */
  const char *scale_y_help; /**< @brief Escalar la figura en y help description.  */
  char * scale_z_arg;	/**< @brief Escalar la figura en z.  */
  char * scale_z_orig;	/**< @brief Escalar la figura en z original value given at command line.  */
  const char *scale_z_help; /**< @brief Escalar la figura en z help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int input_given ;	/**< @brief Whether input was given.  */
  unsigned int output_given ;	/**< @brief Whether output was given.  */
  unsigned int resolution_given ;	/**< @brief Whether resolution was given.  */
  unsigned int raster_wireframe_given ;	/**< @brief Whether raster-wireframe was given.  */
  unsigned int viewport_given ;	/**< @brief Whether viewport was given.  */
  unsigned int rotate_given ;	/**< @brief Whether rotate was given.  */
  unsigned int scale_given ;	/**< @brief Whether scale was given.  */
  unsigned int translate_given ;	/**< @brief Whether translate was given.  */
  unsigned int rotate_x_given ;	/**< @brief Whether rotate-x was given.  */
  unsigned int rotate_y_given ;	/**< @brief Whether rotate-y was given.  */
  unsigned int rotate_z_given ;	/**< @brief Whether rotate-z was given.  */
  unsigned int scale_x_given ;	/**< @brief Whether scale-x was given.  */
  unsigned int scale_y_given ;	/**< @brief Whether scale-y was given.  */
  unsigned int scale_z_given ;	/**< @brief Whether scale-z was given.  */

} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief the description string of the program */
extern const char *gengetopt_args_info_description;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char **argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
