/*
  File autogenerated by gengetopt version 2.22.6
  generated with the following command:
  gengetopt -i cmdline.ggo 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "Render";

const char *gengetopt_args_info_usage = "Usage: renderer [OPTION...]";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "varios algoritmos de computer graphics";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "  -i, --input=STRING            archivo a leer",
  "  -d, --output_dir=STRING       directorio de salida",
  "      --resolution=STRING       resolución de la imagen en la forma <x,y>",
  "      --camera=STRING           coordenadas de la cámara <x,y,z>",
  "      --angleOfView=STRING      angleOfView",
  "      --near=STRING             plano cercano",
  "      --far=STRING              plano lejano",
  "      --rotate=STRING           Rotación x,y,z",
  "      --time=STRING             tiempo a animar en minutos",
  "  -s, --scale=STRING            Escalar la figura en x,y,z",
  "      --scale-x=STRING          Escala en x",
  "      --scale-y=STRING          Escala en y",
  "      --scale-z=STRING          Escala en z",
  "      --wireframe               activa el renderizado wireframe",
  "      --faceHiding              activa el ocultamiento de caras",
  "      --bezier-curve=STRING     curva de bézier a seguir con cuatro puntos de\n                                  control en la forma p1,p2,p3,p4",
  "      --hermite-curve=STRING    curva de hermite a seguir con dos puntos de\n                                  control en la forma p1,p2",
  "      --bezier-surface=STRING   archivo de superficie de bézier con los 16\n                                  puntos",
  "      --hermite-surface=STRING  archivo de superficie de hermite con los 16\n                                  puntos",
  "      --line=STRING             línea a seguir, dos puntos: p1,p2",
  "      --zBuffer                 z bufffer con coordenadas baricéntricas",
  "      --specular=STRING         activa la iluminación especular",
  "      --ambient=STRING          activa la iluminación de ambiente",
  "      --diffuse=STRING          activa la iluminación difusa",
  "      --phong=STRING            modelo de iluminación de Phong",
  "      --gourand=STRING          modelo de iluminación de Gourand",
  "      --flatShading=STRING      activa el renderizado con flatShading",
    0
};

typedef enum {ARG_NO
  , ARG_STRING
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->input_given = 0 ;
  args_info->output_dir_given = 0 ;
  args_info->resolution_given = 0 ;
  args_info->camera_given = 0 ;
  args_info->angleOfView_given = 0 ;
  args_info->near_given = 0 ;
  args_info->far_given = 0 ;
  args_info->rotate_given = 0 ;
  args_info->time_given = 0 ;
  args_info->scale_given = 0 ;
  args_info->scale_x_given = 0 ;
  args_info->scale_y_given = 0 ;
  args_info->scale_z_given = 0 ;
  args_info->wireframe_given = 0 ;
  args_info->faceHiding_given = 0 ;
  args_info->bezier_curve_given = 0 ;
  args_info->hermite_curve_given = 0 ;
  args_info->bezier_surface_given = 0 ;
  args_info->hermite_surface_given = 0 ;
  args_info->line_given = 0 ;
  args_info->zBuffer_given = 0 ;
  args_info->specular_given = 0 ;
  args_info->ambient_given = 0 ;
  args_info->diffuse_given = 0 ;
  args_info->phong_given = 0 ;
  args_info->gourand_given = 0 ;
  args_info->flatShading_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->input_arg = NULL;
  args_info->input_orig = NULL;
  args_info->output_dir_arg = NULL;
  args_info->output_dir_orig = NULL;
  args_info->resolution_arg = NULL;
  args_info->resolution_orig = NULL;
  args_info->camera_arg = NULL;
  args_info->camera_orig = NULL;
  args_info->angleOfView_arg = NULL;
  args_info->angleOfView_orig = NULL;
  args_info->near_arg = NULL;
  args_info->near_orig = NULL;
  args_info->far_arg = NULL;
  args_info->far_orig = NULL;
  args_info->rotate_arg = NULL;
  args_info->rotate_orig = NULL;
  args_info->time_arg = NULL;
  args_info->time_orig = NULL;
  args_info->scale_arg = NULL;
  args_info->scale_orig = NULL;
  args_info->scale_x_arg = NULL;
  args_info->scale_x_orig = NULL;
  args_info->scale_y_arg = NULL;
  args_info->scale_y_orig = NULL;
  args_info->scale_z_arg = NULL;
  args_info->scale_z_orig = NULL;
  args_info->bezier_curve_arg = NULL;
  args_info->bezier_curve_orig = NULL;
  args_info->hermite_curve_arg = NULL;
  args_info->hermite_curve_orig = NULL;
  args_info->bezier_surface_arg = NULL;
  args_info->bezier_surface_orig = NULL;
  args_info->hermite_surface_arg = NULL;
  args_info->hermite_surface_orig = NULL;
  args_info->line_arg = NULL;
  args_info->line_orig = NULL;
  args_info->specular_arg = NULL;
  args_info->specular_orig = NULL;
  args_info->ambient_arg = NULL;
  args_info->ambient_orig = NULL;
  args_info->diffuse_arg = NULL;
  args_info->diffuse_orig = NULL;
  args_info->phong_arg = NULL;
  args_info->phong_orig = NULL;
  args_info->gourand_arg = NULL;
  args_info->gourand_orig = NULL;
  args_info->flatShading_arg = NULL;
  args_info->flatShading_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->input_help = gengetopt_args_info_help[2] ;
  args_info->output_dir_help = gengetopt_args_info_help[3] ;
  args_info->resolution_help = gengetopt_args_info_help[4] ;
  args_info->camera_help = gengetopt_args_info_help[5] ;
  args_info->angleOfView_help = gengetopt_args_info_help[6] ;
  args_info->near_help = gengetopt_args_info_help[7] ;
  args_info->far_help = gengetopt_args_info_help[8] ;
  args_info->rotate_help = gengetopt_args_info_help[9] ;
  args_info->time_help = gengetopt_args_info_help[10] ;
  args_info->scale_help = gengetopt_args_info_help[11] ;
  args_info->scale_x_help = gengetopt_args_info_help[12] ;
  args_info->scale_y_help = gengetopt_args_info_help[13] ;
  args_info->scale_z_help = gengetopt_args_info_help[14] ;
  args_info->wireframe_help = gengetopt_args_info_help[15] ;
  args_info->faceHiding_help = gengetopt_args_info_help[16] ;
  args_info->bezier_curve_help = gengetopt_args_info_help[17] ;
  args_info->hermite_curve_help = gengetopt_args_info_help[18] ;
  args_info->bezier_surface_help = gengetopt_args_info_help[19] ;
  args_info->hermite_surface_help = gengetopt_args_info_help[20] ;
  args_info->line_help = gengetopt_args_info_help[21] ;
  args_info->zBuffer_help = gengetopt_args_info_help[22] ;
  args_info->specular_help = gengetopt_args_info_help[23] ;
  args_info->ambient_help = gengetopt_args_info_help[24] ;
  args_info->diffuse_help = gengetopt_args_info_help[25] ;
  args_info->phong_help = gengetopt_args_info_help[26] ;
  args_info->gourand_help = gengetopt_args_info_help[27] ;
  args_info->flatShading_help = gengetopt_args_info_help[28] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_string_field (&(args_info->input_arg));
  free_string_field (&(args_info->input_orig));
  free_string_field (&(args_info->output_dir_arg));
  free_string_field (&(args_info->output_dir_orig));
  free_string_field (&(args_info->resolution_arg));
  free_string_field (&(args_info->resolution_orig));
  free_string_field (&(args_info->camera_arg));
  free_string_field (&(args_info->camera_orig));
  free_string_field (&(args_info->angleOfView_arg));
  free_string_field (&(args_info->angleOfView_orig));
  free_string_field (&(args_info->near_arg));
  free_string_field (&(args_info->near_orig));
  free_string_field (&(args_info->far_arg));
  free_string_field (&(args_info->far_orig));
  free_string_field (&(args_info->rotate_arg));
  free_string_field (&(args_info->rotate_orig));
  free_string_field (&(args_info->time_arg));
  free_string_field (&(args_info->time_orig));
  free_string_field (&(args_info->scale_arg));
  free_string_field (&(args_info->scale_orig));
  free_string_field (&(args_info->scale_x_arg));
  free_string_field (&(args_info->scale_x_orig));
  free_string_field (&(args_info->scale_y_arg));
  free_string_field (&(args_info->scale_y_orig));
  free_string_field (&(args_info->scale_z_arg));
  free_string_field (&(args_info->scale_z_orig));
  free_string_field (&(args_info->bezier_curve_arg));
  free_string_field (&(args_info->bezier_curve_orig));
  free_string_field (&(args_info->hermite_curve_arg));
  free_string_field (&(args_info->hermite_curve_orig));
  free_string_field (&(args_info->bezier_surface_arg));
  free_string_field (&(args_info->bezier_surface_orig));
  free_string_field (&(args_info->hermite_surface_arg));
  free_string_field (&(args_info->hermite_surface_orig));
  free_string_field (&(args_info->line_arg));
  free_string_field (&(args_info->line_orig));
  free_string_field (&(args_info->specular_arg));
  free_string_field (&(args_info->specular_orig));
  free_string_field (&(args_info->ambient_arg));
  free_string_field (&(args_info->ambient_orig));
  free_string_field (&(args_info->diffuse_arg));
  free_string_field (&(args_info->diffuse_orig));
  free_string_field (&(args_info->phong_arg));
  free_string_field (&(args_info->phong_orig));
  free_string_field (&(args_info->gourand_arg));
  free_string_field (&(args_info->gourand_orig));
  free_string_field (&(args_info->flatShading_arg));
  free_string_field (&(args_info->flatShading_orig));
  
  

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->input_given)
    write_into_file(outfile, "input", args_info->input_orig, 0);
  if (args_info->output_dir_given)
    write_into_file(outfile, "output_dir", args_info->output_dir_orig, 0);
  if (args_info->resolution_given)
    write_into_file(outfile, "resolution", args_info->resolution_orig, 0);
  if (args_info->camera_given)
    write_into_file(outfile, "camera", args_info->camera_orig, 0);
  if (args_info->angleOfView_given)
    write_into_file(outfile, "angleOfView", args_info->angleOfView_orig, 0);
  if (args_info->near_given)
    write_into_file(outfile, "near", args_info->near_orig, 0);
  if (args_info->far_given)
    write_into_file(outfile, "far", args_info->far_orig, 0);
  if (args_info->rotate_given)
    write_into_file(outfile, "rotate", args_info->rotate_orig, 0);
  if (args_info->time_given)
    write_into_file(outfile, "time", args_info->time_orig, 0);
  if (args_info->scale_given)
    write_into_file(outfile, "scale", args_info->scale_orig, 0);
  if (args_info->scale_x_given)
    write_into_file(outfile, "scale-x", args_info->scale_x_orig, 0);
  if (args_info->scale_y_given)
    write_into_file(outfile, "scale-y", args_info->scale_y_orig, 0);
  if (args_info->scale_z_given)
    write_into_file(outfile, "scale-z", args_info->scale_z_orig, 0);
  if (args_info->wireframe_given)
    write_into_file(outfile, "wireframe", 0, 0 );
  if (args_info->faceHiding_given)
    write_into_file(outfile, "faceHiding", 0, 0 );
  if (args_info->bezier_curve_given)
    write_into_file(outfile, "bezier-curve", args_info->bezier_curve_orig, 0);
  if (args_info->hermite_curve_given)
    write_into_file(outfile, "hermite-curve", args_info->hermite_curve_orig, 0);
  if (args_info->bezier_surface_given)
    write_into_file(outfile, "bezier-surface", args_info->bezier_surface_orig, 0);
  if (args_info->hermite_surface_given)
    write_into_file(outfile, "hermite-surface", args_info->hermite_surface_orig, 0);
  if (args_info->line_given)
    write_into_file(outfile, "line", args_info->line_orig, 0);
  if (args_info->zBuffer_given)
    write_into_file(outfile, "zBuffer", 0, 0 );
  if (args_info->specular_given)
    write_into_file(outfile, "specular", args_info->specular_orig, 0);
  if (args_info->ambient_given)
    write_into_file(outfile, "ambient", args_info->ambient_orig, 0);
  if (args_info->diffuse_given)
    write_into_file(outfile, "diffuse", args_info->diffuse_orig, 0);
  if (args_info->phong_given)
    write_into_file(outfile, "phong", args_info->phong_orig, 0);
  if (args_info->gourand_given)
    write_into_file(outfile, "gourand", args_info->gourand_orig, 0);
  if (args_info->flatShading_given)
    write_into_file(outfile, "flatShading", args_info->flatShading_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error_occurred = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (! args_info->input_given)
    {
      fprintf (stderr, "%s: '--input' ('-i') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  if (! args_info->resolution_given)
    {
      fprintf (stderr, "%s: '--resolution' option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  if (! args_info->camera_given)
    {
      fprintf (stderr, "%s: '--camera' option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  if (! args_info->angleOfView_given)
    {
      fprintf (stderr, "%s: '--angleOfView' option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  if (! args_info->near_given)
    {
      fprintf (stderr, "%s: '--near' option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  if (! args_info->far_given)
    {
      fprintf (stderr, "%s: '--far' option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  
  /* checks for dependences among options */

  return error_occurred;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };


  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "input",	1, NULL, 'i' },
        { "output_dir",	1, NULL, 'd' },
        { "resolution",	1, NULL, 0 },
        { "camera",	1, NULL, 0 },
        { "angleOfView",	1, NULL, 0 },
        { "near",	1, NULL, 0 },
        { "far",	1, NULL, 0 },
        { "rotate",	1, NULL, 0 },
        { "time",	1, NULL, 0 },
        { "scale",	1, NULL, 's' },
        { "scale-x",	1, NULL, 0 },
        { "scale-y",	1, NULL, 0 },
        { "scale-z",	1, NULL, 0 },
        { "wireframe",	0, NULL, 0 },
        { "faceHiding",	0, NULL, 0 },
        { "bezier-curve",	1, NULL, 0 },
        { "hermite-curve",	1, NULL, 0 },
        { "bezier-surface",	1, NULL, 0 },
        { "hermite-surface",	1, NULL, 0 },
        { "line",	1, NULL, 0 },
        { "zBuffer",	0, NULL, 0 },
        { "specular",	1, NULL, 0 },
        { "ambient",	1, NULL, 0 },
        { "diffuse",	1, NULL, 0 },
        { "phong",	1, NULL, 0 },
        { "gourand",	1, NULL, 0 },
        { "flatShading",	1, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVi:d:s:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'i':	/* archivo a leer.  */
        
        
          if (update_arg( (void *)&(args_info->input_arg), 
               &(args_info->input_orig), &(args_info->input_given),
              &(local_args_info.input_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "input", 'i',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* directorio de salida.  */
        
        
          if (update_arg( (void *)&(args_info->output_dir_arg), 
               &(args_info->output_dir_orig), &(args_info->output_dir_given),
              &(local_args_info.output_dir_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "output_dir", 'd',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* Escalar la figura en x,y,z.  */
        
        
          if (update_arg( (void *)&(args_info->scale_arg), 
               &(args_info->scale_orig), &(args_info->scale_given),
              &(local_args_info.scale_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "scale", 's',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* resolución de la imagen en la forma <x,y>.  */
          if (strcmp (long_options[option_index].name, "resolution") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->resolution_arg), 
                 &(args_info->resolution_orig), &(args_info->resolution_given),
                &(local_args_info.resolution_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "resolution", '-',
                additional_error))
              goto failure;
          
          }
          /* coordenadas de la cámara <x,y,z>.  */
          else if (strcmp (long_options[option_index].name, "camera") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->camera_arg), 
                 &(args_info->camera_orig), &(args_info->camera_given),
                &(local_args_info.camera_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "camera", '-',
                additional_error))
              goto failure;
          
          }
          /* angleOfView.  */
          else if (strcmp (long_options[option_index].name, "angleOfView") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->angleOfView_arg), 
                 &(args_info->angleOfView_orig), &(args_info->angleOfView_given),
                &(local_args_info.angleOfView_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "angleOfView", '-',
                additional_error))
              goto failure;
          
          }
          /* plano cercano.  */
          else if (strcmp (long_options[option_index].name, "near") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->near_arg), 
                 &(args_info->near_orig), &(args_info->near_given),
                &(local_args_info.near_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "near", '-',
                additional_error))
              goto failure;
          
          }
          /* plano lejano.  */
          else if (strcmp (long_options[option_index].name, "far") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->far_arg), 
                 &(args_info->far_orig), &(args_info->far_given),
                &(local_args_info.far_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "far", '-',
                additional_error))
              goto failure;
          
          }
          /* Rotación x,y,z.  */
          else if (strcmp (long_options[option_index].name, "rotate") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->rotate_arg), 
                 &(args_info->rotate_orig), &(args_info->rotate_given),
                &(local_args_info.rotate_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "rotate", '-',
                additional_error))
              goto failure;
          
          }
          /* tiempo a animar en minutos.  */
          else if (strcmp (long_options[option_index].name, "time") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->time_arg), 
                 &(args_info->time_orig), &(args_info->time_given),
                &(local_args_info.time_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "time", '-',
                additional_error))
              goto failure;
          
          }
          /* Escala en x.  */
          else if (strcmp (long_options[option_index].name, "scale-x") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->scale_x_arg), 
                 &(args_info->scale_x_orig), &(args_info->scale_x_given),
                &(local_args_info.scale_x_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "scale-x", '-',
                additional_error))
              goto failure;
          
          }
          /* Escala en y.  */
          else if (strcmp (long_options[option_index].name, "scale-y") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->scale_y_arg), 
                 &(args_info->scale_y_orig), &(args_info->scale_y_given),
                &(local_args_info.scale_y_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "scale-y", '-',
                additional_error))
              goto failure;
          
          }
          /* Escala en z.  */
          else if (strcmp (long_options[option_index].name, "scale-z") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->scale_z_arg), 
                 &(args_info->scale_z_orig), &(args_info->scale_z_given),
                &(local_args_info.scale_z_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "scale-z", '-',
                additional_error))
              goto failure;
          
          }
          /* activa el renderizado wireframe.  */
          else if (strcmp (long_options[option_index].name, "wireframe") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->wireframe_given),
                &(local_args_info.wireframe_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "wireframe", '-',
                additional_error))
              goto failure;
          
          }
          /* activa el ocultamiento de caras.  */
          else if (strcmp (long_options[option_index].name, "faceHiding") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->faceHiding_given),
                &(local_args_info.faceHiding_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "faceHiding", '-',
                additional_error))
              goto failure;
          
          }
          /* curva de bézier a seguir con cuatro puntos de control en la forma p1,p2,p3,p4.  */
          else if (strcmp (long_options[option_index].name, "bezier-curve") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->bezier_curve_arg), 
                 &(args_info->bezier_curve_orig), &(args_info->bezier_curve_given),
                &(local_args_info.bezier_curve_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "bezier-curve", '-',
                additional_error))
              goto failure;
          
          }
          /* curva de hermite a seguir con dos puntos de control en la forma p1,p2.  */
          else if (strcmp (long_options[option_index].name, "hermite-curve") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hermite_curve_arg), 
                 &(args_info->hermite_curve_orig), &(args_info->hermite_curve_given),
                &(local_args_info.hermite_curve_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "hermite-curve", '-',
                additional_error))
              goto failure;
          
          }
          /* archivo de superficie de bézier con los 16 puntos.  */
          else if (strcmp (long_options[option_index].name, "bezier-surface") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->bezier_surface_arg), 
                 &(args_info->bezier_surface_orig), &(args_info->bezier_surface_given),
                &(local_args_info.bezier_surface_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "bezier-surface", '-',
                additional_error))
              goto failure;
          
          }
          /* archivo de superficie de hermite con los 16 puntos.  */
          else if (strcmp (long_options[option_index].name, "hermite-surface") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hermite_surface_arg), 
                 &(args_info->hermite_surface_orig), &(args_info->hermite_surface_given),
                &(local_args_info.hermite_surface_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "hermite-surface", '-',
                additional_error))
              goto failure;
          
          }
          /* línea a seguir, dos puntos: p1,p2.  */
          else if (strcmp (long_options[option_index].name, "line") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->line_arg), 
                 &(args_info->line_orig), &(args_info->line_given),
                &(local_args_info.line_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "line", '-',
                additional_error))
              goto failure;
          
          }
          /* z bufffer con coordenadas baricéntricas.  */
          else if (strcmp (long_options[option_index].name, "zBuffer") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->zBuffer_given),
                &(local_args_info.zBuffer_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "zBuffer", '-',
                additional_error))
              goto failure;
          
          }
          /* activa la iluminación especular.  */
          else if (strcmp (long_options[option_index].name, "specular") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->specular_arg), 
                 &(args_info->specular_orig), &(args_info->specular_given),
                &(local_args_info.specular_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "specular", '-',
                additional_error))
              goto failure;
          
          }
          /* activa la iluminación de ambiente.  */
          else if (strcmp (long_options[option_index].name, "ambient") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->ambient_arg), 
                 &(args_info->ambient_orig), &(args_info->ambient_given),
                &(local_args_info.ambient_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "ambient", '-',
                additional_error))
              goto failure;
          
          }
          /* activa la iluminación difusa.  */
          else if (strcmp (long_options[option_index].name, "diffuse") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->diffuse_arg), 
                 &(args_info->diffuse_orig), &(args_info->diffuse_given),
                &(local_args_info.diffuse_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "diffuse", '-',
                additional_error))
              goto failure;
          
          }
          /* modelo de iluminación de Phong.  */
          else if (strcmp (long_options[option_index].name, "phong") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->phong_arg), 
                 &(args_info->phong_orig), &(args_info->phong_given),
                &(local_args_info.phong_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "phong", '-',
                additional_error))
              goto failure;
          
          }
          /* modelo de iluminación de Gourand.  */
          else if (strcmp (long_options[option_index].name, "gourand") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->gourand_arg), 
                 &(args_info->gourand_orig), &(args_info->gourand_given),
                &(local_args_info.gourand_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "gourand", '-',
                additional_error))
              goto failure;
          
          }
          /* activa el renderizado con flatShading.  */
          else if (strcmp (long_options[option_index].name, "flatShading") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->flatShading_arg), 
                 &(args_info->flatShading_orig), &(args_info->flatShading_given),
                &(local_args_info.flatShading_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "flatShading", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



  if (check_required)
    {
      error_occurred += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
